{% set name = "django-cte" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-cte-{{ version }}.tar.gz
  sha256: 0c1aeef067278a22886151c1d27f6f665a303952d058900e5ca82a24cde40697

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

    # Required for import test but not listed upstream
    - django

test:
  imports:
    - django_cte
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dimagi/django-cte
  summary: Common Table Expressions (CTE) for Django
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
